unit TestuBaralho;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Exceptions, uIBaralho, System.Generics.Collections, uICarta, uBaralho,
  uCarta, SysUtils, Tipos;

type
  // Test methods for class TBaralho

  TestTBaralho = class(TTestCase)
  strict private
    FBaralho: TBaralho;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCreate;
    procedure TestEmbaralharCartas;
    procedure TestAdicionarCarta;
    procedure TestCortarBaralho;
    procedure TestRetirarCarta;
  end;

implementation

procedure TestTBaralho.SetUp;
begin
  FBaralho := TBaralho.Create;
end;

procedure TestTBaralho.TearDown;
begin
  FBaralho.Free;
  FBaralho := nil;
end;

procedure TestTBaralho.TestEmbaralharCartas;
begin
  FBaralho.EmbaralharCartas;
  // TODO: Validate method results
end;

procedure TestTBaralho.TestAdicionarCarta;
var
  carta: ICarta;
begin
  // TODO: Setup method call parameters
  FBaralho.AdicionarCarta(carta);
  // TODO: Validate method results
end;

procedure TestTBaralho.TestCortarBaralho;
var
  cartasNecessarias: Integer;
  sentidoCorte: tpSentidoCorte;
  posicaoCorte: Integer;
begin
  // TODO: Setup method call parameters
  FBaralho.CortarBaralho(posicaoCorte, sentidoCorte, cartasNecessarias);
  // TODO: Validate method results
end;

procedure TestTBaralho.TestCreate;
var
  FTestBaralho : TBaralho;
begin
  FTestBaralho := TBaralho.Create;

  CheckEquals(44, FTestBaralho.QuantidadeCartas, 'Não foram criadas 44 cartas')
end;

procedure TestTBaralho.TestRetirarCarta;
var
  ReturnValue: ICarta;
begin
  ReturnValue := FBaralho.RetirarCarta;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTBaralho.Suite);
end.

