unit TestuCartas;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Tipos, uCarta, uICarta;

type
  // Test methods for class TCartas

  TestTCartas = class(TTestCase)
  strict private
    FCarta: TCarta;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCompararNaipe;
    procedure TesCompararValor;
    procedure TesCompararIgual;
    procedure TesCompararManilha;
  end;

implementation

procedure TestTCartas.SetUp;
begin
  FCarta := TCarta.Create(vcSeis, ncOuros);
end;

procedure TestTCartas.TearDown;
begin
  FCarta.Free;
  FCarta := nil;
end;

procedure TestTCartas.TesCompararValor;
var
  ReturnValue: tpResultadoComparacao;
  cartaManilha: ICarta;
  segundaCarta: ICarta;
begin
  cartaManilha := TCarta.Create(vcSete, ncPaus);
  segundaCarta := TCarta.Create(vcTres, ncCopas);

  ReturnValue := FCarta.CompararCartas(segundaCarta, cartaManilha);
  CheckTrue((rcMenor = ReturnValue), 'Erro na comparação de cartas - Seis e Três');
end;

procedure TestTCartas.TesCompararManilha;
var
  ReturnValue: tpResultadoComparacao;
  cartaManilha: ICarta;
  segundaCarta: ICarta;
begin
  cartaManilha := TCarta.Create(vcQuatro, ncPaus);
  segundaCarta := TCarta.Create(vcQuatro, ncOuros);

  ReturnValue := FCarta.CompararCartas(segundaCarta, cartaManilha);

  CheckTrue((rcMenor = ReturnValue), 'Erro na comparação de cartas - Seis e Sete Ouros');
end;

procedure TestTCartas.TesCompararIgual;
var
  ReturnValue: tpResultadoComparacao;
  cartaManilha: ICarta;
  segundaCarta: ICarta;
begin
  cartaManilha := TCarta.Create(vcCinco, ncPaus);
  segundaCarta := TCarta.Create(vcSeis, ncCopas);

  ReturnValue := FCarta.CompararCartas(segundaCarta, cartaManilha);

  CheckTrue((rcIgual = ReturnValue), 'Erro na comparação de cartas - Seis de Paus e Seis de Copas');
end;

procedure TestTCartas.TestCompararNaipe;
var
  ReturnValue: tpResultadoComparacao;
  cartaManilha: ICarta;
  segundaCarta: ICarta;
begin
  cartaManilha := TCarta.Create(vcSeis, ncPaus);
  segundaCarta := TCarta.Create(vcSeis, ncCopas);

  ReturnValue := FCarta.CompararCartas(segundaCarta, cartaManilha);

  CheckTrue((rcMenor = ReturnValue), 'Erro na comparação de cartas - Zap e Copas');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCartas.Suite);
end.

